"""
Read-only test-batch export: fetches N distinct cards (deduped by oracle_id)
directly from Supabase's mtg_cards table, embeds them via the local TEI
service (Qwen/Qwen3-Embedding-0.6B, 1024 dims), and writes plain SQL INSERT
statements for vecs.mtg_nodes to a .sql file.

Reads mtg_cards directly (NOT internal.v_cards_for_ingestion) because every
row in Supabase already has is_embedded=true (the whole 27.5k-card catalog
was embedded before, matching the existing full_mtg_vector_db.zip dump), so
the ingestion view - which filters on that flag - currently returns nothing.
Does NOT touch Supabase (no writes at all) and does NOT require a local
Postgres - the resulting file can be applied with psql on any machine that
already has the vecs.mtg_nodes schema (db_setup/full_mtg_vector_db_schema.sql).

The embedding text/metadata shape (name, cmc, type, colors, keywords,
oracle_id, legalities, phases, mechanics + _node_content etc. via
node_to_metadata_dict) matches what's already in the existing dump (verified
against a sample row), except the text itself is built locally from
name/type_line/oracle_text/keywords (same approach as embed_cards_local.py)
since the original embedding_text template lives server-side in the now-empty
ingestion view and isn't reproducible from here.

Prerequisites:
- The `embedder` service from docker-compose.yaml running (TEI on :8082)
- backend/.env has SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY set

Run from backend/ with the repo's venv active and .env already sourced into the shell:
    python embed_cards_to_sql.py --count 500 --out db_setup/test_batch_500.sql
"""
import argparse
import json
import os
import sys
import time

sys.path.insert(0, os.getcwd())

from supabase import create_client
from llama_index.core import Document
from llama_index.core.vector_stores.utils import node_to_metadata_dict
from llama_index.embeddings.text_embeddings_inference import TextEmbeddingsInference

PAGE_SIZE = 200
MODEL_NAME = "Qwen/Qwen3-Embedding-0.6B"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Embed N distinct cards (read-only) and export as SQL INSERTs for vecs.mtg_nodes"
    )
    parser.add_argument("--count", type=int, required=True, help="Number of distinct cards (by oracle_id) to embed")
    parser.add_argument("--out", type=str, required=True, help="Output .sql file path")
    return parser.parse_args()


def fetch_distinct_cards(supabase, total):
    """Reads mtg_cards ordered by id, keeping the first row seen per oracle_id,
    until `total` distinct cards have been collected."""
    by_oracle_id = {}
    offset = 0
    while len(by_oracle_id) < total:
        rows = (
            supabase.table("mtg_cards")
            .select("*")
            .order("id")
            .range(offset, offset + PAGE_SIZE - 1)
            .execute()
            .data
        )
        if not rows:
            break
        for row in rows:
            oid = row["oracle_id"]
            if oid not in by_oracle_id:
                by_oracle_id[oid] = row
        offset += PAGE_SIZE
    return list(by_oracle_id.values())[:total]


def build_card_node(row):
    keywords = row.get("keywords") or []
    colors = row.get("colors") or []
    legalities = row.get("legalities") or {}
    cmc = row.get("cmc")
    if cmc is None:
        cmc = 0

    text = (
        f"{row['name']}\n{row.get('type_line') or ''}\n{row.get('oracle_text') or ''}\n"
        f"Keywords: {', '.join(keywords)}"
    )
    metadata = {
        "cmc": cmc,
        "name": row["name"],
        "type": "card",
        "colors": colors,
        "phases": [],
        "keywords": keywords,
        "mechanics": [],
        "oracle_id": row["oracle_id"],
        "legalities": legalities,
    }

    return Document(
        text=text,
        id_=str(row["oracle_id"]),
        metadata=metadata,
        excluded_llm_metadata_keys=["legalities"],
    )


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def main():
    args = parse_args()
    supabase = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_ROLE_KEY"])

    print(f"--- Fetching {args.count} distinct cards (read-only, mtg_cards) ---")
    rows = fetch_distinct_cards(supabase, args.count)
    print(f"Fetched {len(rows)} distinct cards (Supabase not modified)")

    nodes = [build_card_node(row) for row in rows]

    embedder = TextEmbeddingsInference(
        model_name=MODEL_NAME,
        base_url=os.environ.get("EMBEDDER_BASE_URL") or "http://localhost:8082",
    )

    print(f"\n--- Embedding {len(nodes)} cards via TEI, writing SQL to {args.out} ---")
    start = time.time()

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("-- Read-only test batch export, generated by embed_cards_to_sql.py\n")
        f.write("-- Does not reflect or require any Supabase is_embedded state change.\n\n")

        for i, node in enumerate(nodes, start=1):
            vec = embedder.get_text_embedding(node.text)

            metadata = node_to_metadata_dict(node, remove_text=False)
            vector_str = "[" + ",".join(map(str, vec)) + "]"
            metadata_json = json.dumps(metadata, ensure_ascii=False)

            f.write(
                "INSERT INTO vecs.mtg_nodes (id, vec, metadata) VALUES "
                f"('{sql_escape(node.id_)}', '{vector_str}'::vector, '{sql_escape(metadata_json)}'::jsonb) "
                "ON CONFLICT (id) DO UPDATE SET vec = EXCLUDED.vec, metadata = EXCLUDED.metadata;\n"
            )

            if i % 25 == 0 or i == len(nodes):
                elapsed = time.time() - start
                rate = i / elapsed
                print(f"  {i}/{len(nodes)} embedded ({elapsed:.1f}s elapsed, {rate:.2f} cards/s)")

    total_time = time.time() - start
    print(f"\nDone. {len(nodes)} cards embedded and written to {args.out} in {total_time:.1f}s.")


if __name__ == "__main__":
    main()
