FROM ghcr.io/huggingface/text-embeddings-inference:cpu-1.9

CMD ["--model-id", "Qwen/Qwen3-Embedding-0.6B", "--max-batch-tokens", "2048", "--max-concurrent-requests", "8", "--max-client-batch-size", "8"]
